const users = [
    {
        username: "amit_kumar1",
        name: "Amit Kumar",
        email: "amit1@gmail.com",
        password: "pass123",
        age: "22",
        isMarried: false,
    },
    {
        username: "sumit_sharma2",
        name: "Sumit Sharma",
        email: "sumit2@gmail.com",
        password: "pass123",
        age: "25",
        isMarried: true,
    },
    {
        username: "rohit_verma3",
        name: "Rohit Verma",
        email: "rohit3@gmail.com",
        password: "pass123",
        age: "28",
        isMarried: false,
    },
    {
        username: "ankit_singh4",
        name: "Ankit Singh",
        email: "ankit4@gmail.com",
        password: "pass123",
        age: "24",
        isMarried: false,
    },
    {
        username: "vikas_yadav5",
        name: "Vikas Yadav",
        email: "vikas5@gmail.com",
        password: "pass123",
        age: "30",
        isMarried: true,
    },
    {
        username: "deepak_mishra6",
        name: "Deepak Mishra",
        email: "deepak6@gmail.com",
        password: "pass123",
        age: "21",
        isMarried: false,
    },
    {
        username: "rahul_chauhan7",
        name: "Rahul Chauhan",
        email: "rahul7@gmail.com",
        password: "pass123",
        age: "27",
        isMarried: true,
    },
    {
        username: "karan_gupta8",
        name: "Karan Gupta",
        email: "karan8@gmail.com",
        password: "pass123",
        age: "26",
        isMarried: false,
    },
    {
        username: "pankaj_jain9",
        name: "Pankaj Jain",
        email: "pankaj9@gmail.com",
        password: "pass123",
        age: "23",
        isMarried: false,
    },
    {
        username: "sandeep_kumar10",
        name: "Sandeep Kumar",
        email: "sandeep10@gmail.com",
        password: "pass123",
        age: "29",
        isMarried: true,
    },
    {
        username: "ajay_singh11",
        name: "Ajay Singh",
        email: "ajay11@gmail.com",
        password: "pass123",
        age: "20",
        isMarried: false,
    },
    {
        username: "manoj_kumar12",
        name: "Manoj Kumar",
        email: "manoj12@gmail.com",
        password: "pass123",
        age: "31",
        isMarried: true,
    },
    {
        username: "rajesh_patel13",
        name: "Rajesh Patel",
        email: "rajesh13@gmail.com",
        password: "pass123",
        age: "19",
        isMarried: false,
    },
    {
        username: "prakash_jha14",
        name: "Prakash Jha",
        email: "prakash14@gmail.com",
        password: "pass123",
        age: "32",
        isMarried: true,
    },
    {
        username: "bidhit_chaudhary15",
        name: "Bidhit Chaudhary",
        email: "bidhit15@gmail.com",
        password: "pass123",
        age: "23",
        isMarried: false,
    },
];
module.exports = users;
